let data = [
    {
      id: 1,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i1.jpg",
    },
    {
      id: 2,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i2.jpg",
    },
    {
      id: 3,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i3.jpg",
    },
    {
      id: 4,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i4.jpg",
    },
    {
      id: 5,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i5.jpg",
    },
    {
      id: 6,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i6.jpg",
    },
    {
      id: 7,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i6.jpg",
    },
    {
      id: 8,
      name: "pta kar lo",
      role: "pta karo",
      description: "hall aao",
      facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
      imgsource: "/team/i6.jpg",
    },
  ];
  
  export default data;
  