let data = [
  {
    id: 1,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 2,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 3,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 4,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 5,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 6,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 7,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 8,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 9,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 10,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 11,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 12,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 13,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 14,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 15,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 16,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 17,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 18,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 19,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
  {
    id: 20,
    name: "pta kar lo",
    role: "pta karo",
    description: "hall aao",
    facebooklink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    instalink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    twitterlink: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    email: "https://www.youtube.com/watch?v=zzGEbXwOcLM",
    imgsource: "/team/i1.jpg",
  },
];

export default data;
